config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, controllers: { sessions: 'users/sessions' }
  root to: 'statics#top'

  resources :unread_books do
    patch :reading, on: :member
    patch :cancel_reading, on: :member
    get :reading_books, on: :collection
    patch :return, on: :member
    get :search, on: :collection
  end

  resources :conversations, only: %i[index create] do
    resources :messages, only: %i[index create]
  end

  resources :finished_books do
    get :others, on: :collection
    get :disposal, on: :collection
  end

  resources :comments, only: :create
  resources :users, only: :show
  resources :concern_books, only: [:index, :create, :destroy]
  resources :progresses, only: [:create, :destroy]
end

app/views/shared/layout/_footer.html.erb
<footer>
  <nav aria-label="breadcrumb">
    <ol class="breadcrumb">
      <li class="breadcrumb-item"><a href="/">Home</a></li>
      <li class="footer-name">©︎ Bookshelf Cleaner</li>
    </ol>
  </nav>
</footer>

app/views/shared/layout/_header.html.erb
<header>
  <nav data-turbolinks="false" class="navbar navbar-expand-lg navbar-dark bg-primary">
    <a class="navbar-brand" href="/">Bookshelf Cleaner</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <% if user_signed_in? %>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              未読書籍
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <a class="dropdown-item" href="/unread_books">未読書籍一覧</a>
              <a class="dropdown-item" href="/unread_books/reading_books">読書中書籍一覧</a>
            </div>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/finished_books">既読書籍一覧</a>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              他のユーザー
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <a class="dropdown-item" href="/conversations">スレッド一覧</a>
              <a class="dropdown-item" href="/finished_books/others">他ユーザーの既読書籍一覧</a>
              <a class="dropdown-item" href="/finished_books/disposal">他ユーザーの処分予定書籍一覧</a>
            </div>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/unread_books/search">書籍検索</a>
          </li>
        </ul>
        <ul class="navbar-nav">
          <li class="nav-item nav-right dropdown">
            <button type="button" class="btn bmd-btn-icon nav-link" id="navbarDropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <i class="material-icons">more_vert</i>
            </button>
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
              <%= link_to 'マイページ', user_path(current_user), class: 'dropdown-item' %>
              <%= link_to '登録情報変更', edit_user_registration_path, class: 'dropdown-item' %>
              <%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: 'dropdown-item', data: { confirm: 'ログアウトしますか？' } %>
            </div>
          </li>
        </ul>
      </div>
    <% else %>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav">
          <li class="nav-item nav-right">
            <%= link_to 'ログイン', new_user_session_path, class: 'nav-link' %>
          </li>
          <li class="nav-item nav-right">
            <%= link_to '新規登録', new_user_registration_path, class: 'nav-link'%>
          </li>
        </ul>
      </div>
    <% end %>
  </nav>
</header>

app/views/shared/layout/_side_search.html.erb
<h5 class="index-search-title">書籍検索</h5>
<%= search_form_for @q do |f| %>
  <div class="form-group index-search">
    <%= f.label :title_or_author_cont, 'キーワード', class: 'bmd-label-floating' %>
    <%= f.search_field :title_or_author_cont, class: 'form-control' %>
  </div>

  <div class="form-group select-form">
    <%= f.label :status_eq, 'ステータス', class: 'bmd-label-floating' %>
    <%= f.select :status_eq, UnreadBook.statuses.map {|k, v| [I18n.t("enums.unread_book.status.#{k}"), v]}, { include_blank: true, selected: '' }, {class: 'custom-select'} %>
  </div>

  <%= f.submit '検索', class: 'btn btn-primary btn-raised' %>
<% end %>
<%= link_to '検索結果を戻す', unread_books_path, class: 'btn btn-warning', data: {turbolinks: false} %>

app/views/shared/layout/_sidebar.html.erb
<div class="card top-card">
  <div class="card-header">
    <%= "#{current_user.name} さんのステータス" %>
  </div>
  <ul class="list-group list-group-flush">
    <li class="list-group-item">直近30日の読破数: <%= current_user.finished_books.where(created_at: DateTime.now - 30..DateTime.now).count %>冊 </li>
    <li class="list-group-item">読破済み書籍数: <%= current_user.finished_books.count %>冊</li>
    <li class="list-group-item list-alert">処分期限超過書籍数: <%= current_user.finished_books.where('status = ? AND desposal_expired < ?', 2, DateTime.now).count %>冊</li>
  </ul>
  <div class="card-footer">
    <small><%= link_to 'マイページ', user_path(current_user), class: 'btn btn-primary', data: {turbolinks: false} %> </small>
    <small><%= link_to '気になる書籍一覧', concern_books_path, class: 'btn btn-primary', data: {turbolinks: false} %> </small>
  </div>
</div>