config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, controllers: { sessions: 'users/sessions' }
  root to: 'statics#top'

  resources :unread_books do
    patch :reading, on: :member
    patch :cancel_reading, on: :member
    get :reading_books, on: :collection
    patch :return, on: :member
    get :search, on: :collection
  end

  resources :conversations, only: %i[index create] do
    resources :messages, only: %i[index create]
  end

  resources :finished_books do
    get :others, on: :collection
    get :disposal, on: :collection
  end

  resources :comments, only: :create
  resources :users, only: :show
  resources :concern_books, only: [:index, :create, :destroy]
  resources :progresses, only: [:create, :destroy]
end

app/models/finished_book.rb
# == Schema Information
#
# Table name: finished_books
#
#  id               :bigint           not null, primary key
#  author           :string           not null
#  desposal_expired :date
#  image            :text
#  impression       :text
#  status           :integer          default("reread"), not null
#  title            :string           not null
#  created_at       :datetime         not null
#  updated_at       :datetime         not null
#  user_id          :bigint
#
# Indexes
#
#  index_finished_books_on_user_id  (user_id)
#
# Foreign Keys
#
#  fk_rails_...  (user_id => users.id)
#

class FinishedBook < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :concern_books, dependent: :destroy
  validates :title, presence: true
  validates :author, presence: true
  validates :impression, length: { maximum: 300 }
  validates :desposal_expired, date: { allow_blank: true }
  acts_as_taggable
  enum status: %i[reread keep disposal_soon disposal]
  mount_uploader :image, ImageUploader

  scope :standard, ->  { order(created_at: :desc)}
end

app/controllers/finished_books_controller.rb
class FinishedBooksController < ApplicationController
  before_action :authenticate_user!
  before_action :set_book, only: %i[show edit update destroy]

  def index
    @q = current_user.finished_books.ransack(params[:q])
    @finished_books = @q.result(distinct: true).page(params[:page]).per(10).standard
  end

  def others
    @q = FinishedBook.where.not(user_id: current_user.id).ransack(params[:q])
    @finished_books = @q.result(distinct: true).page(params[:page]).per(10).standard
  end

  def disposal
    @q = FinishedBook.where.not(user_id: current_user.id).where(status: 2).ransack(params[:q])
    @finished_books = @q.result(distinct: true).page(params[:page]).per(10).standard
  end

  def new
    @unread_book = current_user.unread_books.find(params[:id])
    @finished_book = current_user.finished_books.new
    @finished_book.assign_attributes(title: params[:title],author: params[:author], tag_list: params[:tags])
    @image = params[:image]
  end

  def create
    @unread_book = current_user.unread_books.find(params[:finished_book][:unread_book][:id])
    @finished_book = current_user.finished_books.new(book_params)
    @finished_book.image = @unread_book.image if @unread_book.image.present?
    if @finished_book.save
      @unread_book.destroy
      redirect_to root_path, success: '書籍読破おめでとうございます！'
    else
      render :new
    end
  end

  def edit
    redirect_to root_path, danger: '他のユーザーの書籍です' if @finished_book.user != current_user
  end

  def show
    @comment = @finished_book.comments.new
    @comments = @finished_book.comments.page(params[:page]).per(5).order(created_at: :desc)
  end

  def update
    if @finished_book.update(book_params)
      redirect_to finished_books_path, info: '既読書籍情報を更新しました'
    else
      render :edit
    end
  end

  def destroy
    @finished_book.destroy
    redirect_to finished_books_path, danger: '既読書籍を削除しました'
  end

  private

  def book_params
    params.require(:finished_book).permit(:title, :author, :status, :desposal_expired, :impression, :unread_book, :image, :tag_list, :image_cache)
  end

  def set_book
    @finished_book = FinishedBook.find(params[:id])
  end
end

app/helpers/finished_books_helper.rb
module FinishedBooksHelper
end

app/views/finished_books/disposal.html.erb
<div class="books_wrapper">

  <div class="container">
    <div class="row">
      <div class="col-sm-2 search-index-form">
        <h5 class="index-search-title">書籍検索</h5>
        <%= search_form_for @q, url: disposal_finished_books_path do |f| %>
          <div class="form-group index-search">
            <%= f.label :title_or_author_cont, 'キーワード', class: 'bmd-label-floating' %>
            <%= f.search_field :title_or_author_cont, class: 'form-control' %>
          </div>

          <%= f.submit '検索', class: 'btn btn-primary btn-raised' %>
        <% end %>
        <%= link_to '検索結果を戻す', disposal_finished_books_path, class: 'btn btn-warning', data: {turbolinks: false} %>
      </div>

      <div class="col-sm-10 index-table">
        <div class="index-table-content">
          <h2 class="unread-top">処分予定書籍</h2>
          <div class="table-responsive">
            <table class="table table-striped">
              <thead>
                <tr>
                  <th class="book-title" style="width: 30%">書籍名</th>
                  <th class="book-description" style="width: 13%">ユーザー名</th>
                  <th class="book-description" style="width: 15%">処分予定時期</th>
                  <th class="book-description" style="width: 20%">メッセージを送る</th>
                  <th class="book-description" style="width: 22%">お気に入り</th>
                </tr>
              </thead>
              <tbody>
                <% @finished_books.each do |book| %>
                  <tr>
                    <td class="book-title"><%= link_to book.title, finished_book_path(book), class: 'book-info', data: {turbolinks: false} %>
                      <div class="only-responsive">
                        <%= link_to 'メッセージを送る', conversations_path(sender_id: current_user.id, recipient_id: book.user.id), method: :post, class: 'btn btn-primary btn-sm' %>
                        <% if current_user.concerned?(book) %>
                          <%= link_to '気になる書籍から外す', concern_book_path(current_user.concern_books.find_by(finished_book_id: book.id)), method: :delete, class: 'btn btn-secondary btn-sm' %>
                        <% else %>
                          <%= link_to '気になる書籍に追加する', concern_books_path(finished_book_id: book.id), method: :post, class: 'btn btn-success btn-sm' %>
                        <% end %>
                      </div>
                    </td>
                    <td class="book-description"><%= link_to book.user.name, user_path(book.user), data: {turbolinks: false} %></td>
                    <td class="book-description"><%= book.desposal_expired %></td>
                    <td class="book-description"><%= link_to 'メッセージを送る', conversations_path(sender_id: current_user.id, recipient_id: book.user.id), method: :post, class: 'btn btn-primary btn-sm btn-raised' %></td>
                    <% if current_user.concerned?(book) %>
                      <td class="book-description"><%= link_to '気になる書籍から外す', concern_book_path(current_user.concern_books.find_by(finished_book_id: book.id)), method: :delete, class: 'btn btn-secondary btn-sm btn-raised' %></td>
                    <% else %>
                      <td class="book-description"><%= link_to '気になる書籍に追加する', concern_books_path(finished_book_id: book.id), method: :post, class: 'btn btn-success btn-raised btn-sm' %></td>
                    <% end %>
                  </tr>
                <% end %>
              </tbody>
            </table>
          </div>

        <%= paginate @finished_books %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/finished_books/edit.html.erb
<h2 class="unread-top">読破書籍編集画面</h2>

<% if @finished_book.errors.present? %>
  <ul>
    <% @finished_book.errors.full_messages.each do |msg|%>
      <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>

<div class="unread_form_wrapper">
  <%= form_with model: @finished_book, local: true do |f| %>
    <div>
      <% if @finished_book.image && @finished_book.image.url %>
        <%= image_tag @finished_book.image.url, size: '140x200' %>
        <p>by Google Search </p>
      <% else %>
        <%= image_tag "no_image.png", size: '140x200' %>
      <% end %>
      <%= f.hidden_field :image_cache %>
    </div>

    <div class="form-group">
      <%= f.label :title, class: 'bmd-label-floating' %>
      <%= f.text_field :title, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= f.label :author, class: 'bmd-label-floating' %>
      <%= f.text_field :author, class: 'form-control' %>
    </div>


    <div class="form-group select-form">
      <%= f.label :status, class: 'bmd-label-floating' %>
      <%= f.select :status, FinishedBook.statuses.keys.map {|k| [I18n.t("enums.finished_book.status.#{k}"), k]}, { selected: FinishedBook.statuses[@finished_book.status] }, {class: 'custom-select', id: 'finish_status'} %>
    </div>

    <div class="form-group select-date">
      <%= f.label :desposal_expired, class: 'bmd-label-floating' %>
      <%= f.date_field :desposal_expired, id: 'disposal_disabled', disabled: true %>
    </div>

    <div class="form-group">
      <%= f.label :tag_list, class: 'bmd-label-floating' %>
      <%= text_field_tag 'finished_book[tag_list]', @finished_book.tag_list.join(","), class: 'form-control', placeholder: 'タグを複数入力する場合は「,」で区切ってください' %>
    </div>

    <div class="form-group">
      <%= f.label :impression, class: 'bmd-label-floating' %>
      <%= f.text_area :impression, class: 'form-control', rows: '5' %>
    </div>

    <%= f.submit '更新する', class: 'btn btn-primary' %>
  <% end %>
</div>
<%= javascript_include_tag 'finished_books.js' %>

app/views/finished_books/index.html.erb
<div class="books_wrapper">

  <div class="container">
    <div class="row">
      <div class="col-sm-2 search-index-form">
        <h5 class="index-search-title">書籍検索</h5>
        <%= search_form_for @q do |f| %>
          <div class="form-group index-search">
            <%= f.label :title_or_author_cont, 'キーワード', class: 'bmd-label-floating' %>
            <%= f.search_field :title_or_author_cont, class: 'form-control' %>
          </div>

          <div class="form-group select-form">
            <%= f.label :status_eq, 'ステータス', class: 'bmd-label-floating' %>
            <%= f.select :status_eq, FinishedBook.statuses.map {|k, v| [I18n.t("enums.finished_book.status.#{k}"), v]}, { include_blank: true, selected: '' }, {class: 'custom-select'} %>
          </div>

          <%= f.submit '検索', class: 'btn btn-primary btn-raised' %>
        <% end %>
        <%= link_to '検索結果を戻す', finished_books_path, class: 'btn btn-warning', data: {turbolinks: false} %>
      </div>

      <div class="col-sm-10 index-table">
        <div class="index-table-content">
          <h2 class="unread-top">既読書籍一覧</h2>
          <div class="table-responsive">
            <table class="table table-striped">
              <thead>
                <tr>
                  <th class="book-title" style="width: 35%">書籍名</th>
                  <th class="book-description" style="width: 30%">著者名</th>
                  <th class="book-description" style="width: 15%">ステータス</th>
                  <th class="book-description" style="width: 20%">処分時期</th>
                </tr>
              </thead>
              <tbody>
                <% @finished_books.each do |book| %>
                  <tr>
                    <td class="book-title"><%= link_to book.title, finished_book_path(book), class: 'book-info', data: {turbolinks: false} %></td>
                    <td class="book-description"><%= book.author %></td>
                    <td class="book-description"><%= book.status_i18n %></td>
                    <% if book.desposal_expired.present? %>
                      <td class="book-description"><%= book.desposal_expired %></td>
                    <% else %>
                      <td class="book-description"><%= '未設定' %></td>
                    <% end %>
                  </tr>
                <% end %>
              </tbody>
            </table>
          </div>

        <%= paginate @finished_books %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/finished_books/new.html.erb
<h2 class="unread-top">読破書籍登録画面</h2>

<% if @finished_book.errors.present? %>
  <ul>
    <% @finished_book.errors.full_messages.each do |msg|%>
      <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>

<div class="unread_form_wrapper">
  <%= form_with model: @finished_book, local: true do |f| %>
    <div>
      <% if @image.present? %>
        <%= image_tag @image %>
      <% else %>
        <%= image_tag "no_image.png", size: '140x200' %>
      <% end %>
    </div>

    <div class="form-group">
      <%= f.label :title, class: 'bmd-label-floating' %>
      <%= f.text_field :title, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= f.label :author, class: 'bmd-label-floating' %>
      <%= f.text_field :author, class: 'form-control' %>
    </div>


    <div class="form-group select-form">
      <%= f.label :status, class: 'bmd-label-floating' %>
      <%= f.select :status, FinishedBook.statuses.keys.map {|k| [I18n.t("enums.finished_book.status.#{k}"), k]}, { selected: FinishedBook.statuses[@finished_book.status] }, {class: 'custom-select', id: 'finish_status'} %>
    </div>

    <div class="form-group select-date">
      <%= f.label :desposal_expired, class: 'bmd-label-floating' %>
      <%= f.date_field :desposal_expired, id: 'disposal_disabled', disabled: true %>
    </div>

    <div class="form-group">
      <%= f.label :tag_list, class: 'bmd-label-floating' %>
      <%= text_field_tag 'finished_book[tag_list]', @finished_book.tag_list.join(","), class: 'form-control', placeholder: 'タグを複数入力する場合は「,」で区切ってください' %>
    </div>

    <div class="form-group">
      <%= f.label :impression, class: 'bmd-label-floating' %>
      <%= f.text_area :impression, class: 'form-control', rows: '5' %>
    </div>
    <%= f.fields_for @unread_book do |i| %>
      <%= i.hidden_field :id %>
    <% end %>

    <%= f.submit '登録する', class: 'btn btn-primary' %>
  <% end %>
</div>
<%= javascript_include_tag 'finished_books.js' %>

app/views/finished_books/others.html.erb
<div class="books_wrapper">
  <div class="container">
    <div class="row">
      <div class="col-sm-2 search-index-form">
        <h5 class="index-search-title">書籍検索</h5>
        <%= search_form_for @q, url: others_finished_books_path do |f| %>
          <div class="form-group index-search">
            <%= f.label :title_or_author_cont, 'キーワード', class: 'bmd-label-floating' %>
            <%= f.search_field :title_or_author_cont, class: 'form-control' %>
          </div>

          <div class="form-group select-form">
            <%= f.label :status_eq, 'ステータス', class: 'bmd-label-floating' %>
            <%= f.select :status_eq, FinishedBook.statuses.map {|k, v| [I18n.t("enums.finished_book.status.#{k}"), v]}, { include_blank: true, selected: '' }, {class: 'custom-select'} %>
          </div>

          <%= f.submit '検索', class: 'btn btn-primary btn-raised' %>
        <% end %>
        <%= link_to '検索結果を戻す', others_finished_books_path, class: 'btn btn-warning', data: {turbolinks: false} %>
      </div>

      <div class="col-sm-10 index-table">
        <div class="index-table-content">
          <h2 class="unread-top">他ユーザーの読破書籍</h2>
          <div class="table-responsive">
            <table class="table table-striped">
              <thead>
                <tr>
                  <th class="book-title" style="width: 25%">書籍名</th>
                  <th class="book-description" style="width: 20%">著者名</th>
                  <th class="book-description" style="width: 13%">ユーザー名</th>
                  <th class="book-description" style="width: 20%">メッセージを送る</th>
                  <th class="book-description" style="width: 22%">お気に入り</th>
                </tr>
              </thead>
              <tbody>
                <% @finished_books.each do |book| %>
                  <tr>
                    <td class="book-title"><%= link_to book.title, finished_book_path(book), class: 'book-info', data: {turbolinks: false} %>
                      <div class="only-responsive">
                        <%= link_to 'メッセージを送る', conversations_path(sender_id: current_user.id, recipient_id: book.user.id), method: :post, class: 'btn btn-primary btn-sm' %>
                        <% if current_user.concerned?(book) %>
                          <%= link_to '気になる書籍から外す', concern_book_path(current_user.concern_books.find_by(finished_book_id: book.id)), method: :delete, class: 'btn btn-secondary btn-sm' %>
                        <% else %>
                          <%= link_to '気になる書籍に追加する', concern_books_path(finished_book_id: book.id), method: :post, class: 'btn btn-success btn-sm' %>
                        <% end %>
                      </div>
                    </td>
                    <td class="book-description"><%= book.author %></td>
                    <td class="book-description"><%= link_to book.user.name, user_path(book.user), data: {turbolinks: false} %></td>
                    <td class="book-description"><%= link_to 'メッセージを送る', conversations_path(sender_id: current_user.id, recipient_id: book.user.id), method: :post, class: 'btn btn-primary btn-raised btn-sm' %></td>
                    <% if current_user.concerned?(book) %>
                      <td class="book-description"><%= link_to '気になる書籍から外す', concern_book_path(current_user.concern_books.find_by(finished_book_id: book.id)), method: :delete, class: 'btn btn-secondary btn-sm btn-raised' %></td>
                    <% else %>
                      <td class="book-description"><%= link_to '気になる書籍に追加する', concern_books_path(finished_book_id: book.id), method: :post, class: 'btn btn-success btn-raised btn-sm' %></td>
                    <% end %>
                  </tr>
                <% end %>
              </tbody>
            </table>
          </div>

        <%= paginate @finished_books %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/finished_books/others_books.html.erb
<div class="books_wrapper">
  <h2>他ユーザーが読んだ書籍</h2>
  <%= search_form_for @q, url: others_books_finished_books_path do |f| %>
    <%= f.label :title_or_author_cont, 'タイトルか著者名' %>
    <%= f.search_field :title_or_author_cont %>

    <%= f.submit %>
  <% end %>
  <%= link_to '元に戻す', others_books_finished_books_path %>

  <table>
    <tr>
      <th>書籍名</th>
      <th>著者名</th>
      <th>ユーザー名</th>
      <th>メッセージを送る</th>
      <th>お気に入り</th>
    </tr>
    <% @finished_books.each do |book| %>
      <tr>
        <td><%= link_to book.title, finished_book_path(book) %></td>
        <td><%= book.author %></td>
        <td><%= link_to book.user.name, user_path(book.user) %></td>
        <td><%= link_to 'メッセージを送る', conversations_path(sender_id: current_user.id, recipient_id: book.user.id), method: :post %></td>
        <% if current_user.concerned?(book) %>
          <td><%= link_to '気になる書籍から外す', concern_book_path(current_user.concern_books.find_by(finished_book_id: book.id)), method: :delete %></td>
        <% else %>
          <td><%= link_to '気になる書籍に追加する', concern_books_path(finished_book_id: book.id), method: :post %></td>
        <% end %>
      </tr>
    <% end %>
  </table>
  <%= paginate @finished_books %>
  <%= link_to '新規未読書籍登録', new_unread_book_path %>
</div>

app/views/finished_books/planning_disposal_books.html.erb
<div class="books_wrapper">
  <h2>他ユーザーが読んだ書籍</h2>
  <%= search_form_for @q, url: planning_disposal_books_finished_books_path do |f| %>
    <%= f.label :title_or_author_cont, 'タイトルか著者名' %>
    <%= f.search_field :title_or_author_cont %>

    <%= f.submit %>
  <% end %>
  <%= link_to '元に戻す', planning_disposal_books_finished_books_path %>

  <table>
    <tr>
      <th>書籍名</th>
      <th>著者名</th>
      <th>ユーザー名</th>
      <th>処分予定時期</th>
      <th>メッセージを送る</th>
      <th>お気に入り</th>
    </tr>
    <% @finished_books.each do |book| %>
      <tr>
        <td><%= link_to book.title, finished_book_path(book) %></td>
        <td><%= book.author %></td>
        <td><%= link_to book.user.name, user_path(book.user) %></td>
        <td><%= book.desposal_expired %></td>
        <td><%= link_to 'メッセージを送る', conversations_path(sender_id: current_user.id, recipient_id: book.user.id), method: :post %></td>
        <% if current_user.concerned?(book) %>
          <td><%= link_to '気になる書籍から外す', concern_book_path(current_user.concern_books.find_by(finished_book_id: book.id)), method: :delete %></td>
        <% else %>
          <td><%= link_to '気になる書籍に追加する', concern_books_path(finished_book_id: book.id), method: :post %></td>
        <% end %>
      </tr>
    <% end %>
  </table>
  <%= paginate @finished_books %>
  <%= link_to '新規未読書籍登録', new_unread_book_path %>
</div>

app/views/finished_books/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-3">
      <%= render 'shared/layout/sidebar' %>
    </div>
    <div class="col-sm-9">
      <h2 class="unread-top">書籍詳細画面</h2>
      <div class="card unread-card">
        <div class="responsive-show">
          <div class="row">
            <div class="col-sm-4">
              <div class="book-show-img">
                <% if @finished_book.image.present? %>
                  <%= image_tag @finished_book.image.url, size: '140x200' %><br>
                  <span class="google-note">by Google Search</span>
                <% else %>
                  <%= image_tag "no_image.png", size: '140x200' %>
                <% end %>
              </div>
            </div>
            <div class="col-sm-8">
              <ul class="unread-list">
                <li class="unread-content">書籍名：<%= @finished_book.title %></li>
                <li class="unread-content">著者名：<%= @finished_book.author %></li>
                <% if @finished_book.desposal_expired.present? %>
                  <li class="unread-content">処分予定日：<%= @finished_book.desposal_expired %></li>
                <% end %>
                <li class="unread-content">ステータス：<%= I18n.t("enums.finished_book.status")[:"#{@finished_book.status}"] %></li>
                <% if @finished_book.tags.present? %>
                  <li class="unread-content">
                    タグ：<% @finished_book.tags.each do |tag|%>
                    <span class="book-tag badge badge-pill badge-primary"><%= tag %></span>
                  <% end %>
                  </li>
                <% end %>
                <% if @finished_book.impression.present? %>
                  <li class="unread-content">感想<%= simple_format(@finished_book.impression) %></li>
                <% end %>
              </ul>
              <% if current_user == @finished_book.user %>
                <%= link_to '編集する', edit_finished_book_path(@finished_book), class: 'btn btn-info', data: {turbolinks: false} %>
                <%= link_to '削除する', finished_book_path(@finished_book), method: :delete, data: {confirm: '本当に削除しますか？'}, class: 'btn btn-danger' %>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="progress-wrapper">
  <h3 class="unread-top"><i class="material-icons progress-icon"> comment </i>コメント一覧</h3>
  <%= form_with model: @comment, local: true do |f| %>
    <div class="form-group">
      <%= f.label :content, 'コメント', class: 'bmd-label-floating'  %>
      <%= f.text_area :content, class: 'form-control textarea-form', rows: '5' %>
    </div>
    <%= f.text_field :user_id, value: current_user.id, type: 'hidden' %>
    <%= f.text_field :finished_book_id, value: @finished_book.id, type: 'hidden' %>

    <%= f.submit '投稿する', class: 'btn btn-primary' %>
  <% end %>

  <ul class="progress-list">
    <% @comments.each do |comment| %>
      <% if comment.id.present? %>
        <i class="material-icons">
          comment
        </i>
        <%= react_component("Comment", { content: comment.content, time: comment.created_at, user: comment.user.name }) %>
      <% end %>
    <% end %>
  </ul>
  <%= paginate @comments, class: 'progress-paginate' %>
</div>