config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, controllers: { sessions: 'users/sessions' }
  root to: 'statics#top'

  resources :unread_books do
    patch :reading, on: :member
    patch :cancel_reading, on: :member
    get :reading_books, on: :collection
    patch :return, on: :member
    get :search, on: :collection
  end

  resources :conversations, only: %i[index create] do
    resources :messages, only: %i[index create]
  end

  resources :finished_books do
    get :others, on: :collection
    get :disposal, on: :collection
  end

  resources :comments, only: :create
  resources :users, only: :show
  resources :concern_books, only: [:index, :create, :destroy]
  resources :progresses, only: [:create, :destroy]
end

app/models/unread_book.rb
# == Schema Information
#
# Table name: unread_books
#
#  id              :bigint           not null, primary key
#  author          :string           not null
#  image           :text
#  reading_expired :date
#  status          :integer          default("not_yet"), not null
#  title           :string           not null
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#  user_id         :bigint           not null
#
# Indexes
#
#  index_unread_books_on_user_id  (user_id)
#
# Foreign Keys
#
#  fk_rails_...  (user_id => users.id)
#

class UnreadBook < ApplicationRecord
  belongs_to :user
  enum status: %i[not_yet reading]
  validates :title, presence: true
  validates :author, presence: true
  validates :reading_expired, date: { allow_blank: true }
  acts_as_taggable
  mount_uploader :image, ImageUploader

  scope :standard, ->  { order(created_at: :desc)}

end

app/controllers/unread_books_controller.rb
class UnreadBooksController < ApplicationController
  require 'net/http'
  require 'uri'
  require 'json'
  before_action :set_book, only: %i[show edit update destroy]
  before_action :authenticate_user!

  def index
    @q = current_user.unread_books.ransack(params[:q])
    @unread_books = @q.result(distinct: true).page(params[:page]).per(10).standard
  end

  def reading
    @reading_book = UnreadBook.find(params[:id])
    if @reading_book.not_yet?
      @reading_book.update(status: 1)
      redirect_to unread_books_path, info: "#{@reading_book.title}を読書中書籍に登録しました"
    else
      redirect_to unread_books_path, warning: 'すでに読書中の書籍です'
    end
  end

  def cancel_reading
    @reading_book = UnreadBook.find(params[:id])
    if @reading_book.reading?
      @reading_book.update(status: 0)
      redirect_to unread_books_path, info: "#{@reading_book.title}を積読に戻しました"
    else
      redirect_to unread_books_path, warning: '積読書籍です'
    end
  end

  def reading_books
    @progresses = current_user.progresses.order(created_at: :desc).first(10)
    @progress = Progress.new
    @reading_books = current_user.unread_books.where(status: 1).page(params[:page]).per(4).standard
  end

  def return
    @reading_book = UnreadBook.find(params[:id])
    @reading_book.update(status: 0)
    redirect_to reading_books_unread_books_path, warning: '未読書籍に戻しました'
  end

  def search
    if params[:looking_for]
      @search_term = params[:looking_for]
      # 書籍のページ送り用
      @number = params[:number].to_i
      uri = URI.parse(URI.encode("https://www.googleapis.com/books/v1/volumes?q=#{@search_term}&Country=JP&startIndex=#{@number}"))
      json = Net::HTTP.get(uri)
      result = JSON.parse(json)
      if result['totalItems'] != 0 && result['totalItems'].present?
        @max_books = result['totalItems']
        @books = result['items']
        @search_books = []
        @books.each do |book|
          @search_books << {
            title: book['volumeInfo']['title'],
            author: book['volumeInfo']['authors']&.join(','),
            image: book['volumeInfo']['imageLinks'] && book['volumeInfo']['imageLinks']['smallThumbnail']
          }
        end
      end
    end
  end

  def new
    @book_image = params[:image]
    @unread_book = current_user.unread_books.new(search_params)
  end

  def create
    @book_image = params[:unread_book][:image]
    @unread_book = current_user.unread_books.new(book_params)
    @unread_book.remote_image_url = @book_image
    if @unread_book.save
      redirect_to unread_books_path, success: "#{@unread_book.title}を未読書籍に登録しました"
    else
      render :new
    end
  end

  def show; end

  def edit
    @unread_book.image.cache!
  end

  def update
    if @unread_book.update(book_params)
      redirect_to unread_books_path, info: '未読書籍情報を更新しました'
    else
      render :edit
    end
  end

  def destroy
    @unread_book.destroy
    redirect_to unread_books_path, danger: '書籍情報を削除しました'
  end

  private

  # 検索した書籍の情報を登録画面に許可するため
  def search_params
    params.permit(:title, :author)
  end

  def book_params
    params.require(:unread_book).permit(:title, :author, :status, :reading_expired, :tag_list, :image, :image_cache)
  end

  def set_book
    @unread_book = current_user.unread_books.find(params[:id])
  end
end

app/helpers/unread_books_helper.rb
module UnreadBooksHelper
end

app/views/unread_books/_form.html.erb
<% if book.errors.present? %>
  <ul>
    <% book.errors.full_messages.each do |msg|%>
      <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>

<%= form_with model: book, local: true do |f| %>
  <div>
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div>
    <%= f.label :author %>
    <%= f.text_field :author %>
  </div>

  <div>
    <%= image_tag @book_image %>
    画像
    <%= f.hidden_field :image, value: @book_image %>
  </div>

  <div>
    <%= f.label :status %>
    <%= f.select :status, UnreadBook.statuses.keys, selected: UnreadBook.statuses[book.status] %>
  </div>

  <div>
    <%= f.label :reading_expired %>
    <%= f.date_select(
                  :reading_expired,
                  use_year_number: true,
                  use_month_number: true,
                  use_day_number: true,
                  start_year: Time.now.year,
                  end_year: Time.now.year + 10
    ) %>
  </div>

  <div>
    <%= f.label :tag_list %>
    <%= text_field_tag 'unread_book[tag_list]', @unread_book.tag_list.join(",") %>
  </div>

  <%= f.submit %>
<% end %>

app/views/unread_books/edit.html.erb
<h2 class="unread-top">未読書籍編集画面</h2>

<% if @unread_book.errors.present? %>
  <ul>
    <% @unread_book.errors.full_messages.each do |msg|%>
      <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>

<div class="unread_form_wrapper">
  <%= form_with model: @unread_book, local: true do |f| %>
    <div>
      <% if @unread_book.image && @unread_book.image.url %>
        <%= image_tag @unread_book.image.url, size: '140x200' %>
        <p>by Google Search </p>
      <% else %>
        <%= image_tag "no_image.png", size: '140x200' %>
      <% end %>
      <%= f.hidden_field :image_cache %>
    </div>

    <div class="form-group">
      <%= f.label :title, class: 'bmd-label-floating' %>
      <%= f.text_field :title, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= f.label :author, class: 'bmd-label-floating' %>
      <%= f.text_field :author, class: 'form-control' %>
    </div>


    <div class="form-group select-form">
      <%= f.label :status, class: 'bmd-label-floating' %>
      <%= f.select :status, UnreadBook.statuses.keys.map {|k| [I18n.t("enums.unread_book.status.#{k}"), k]}, { selected: UnreadBook.statuses[@unread_book.status] }, {class: 'custom-select'} %>
    </div>

    <div class="form-group select-date">
      <%= f.label :reading_expired, class: 'bmd-label-floating' %>
      <%= f.date_field :reading_expired %>
    </div>

    <div class="form-group">
      <%= f.label :tag_list, class: 'bmd-label-floating' %>
      <%= text_field_tag 'unread_book[tag_list]', @unread_book.tag_list.join(","), class: 'form-control', placeholder: 'タグを複数入力する場合は「,」で区切ってください' %>
    </div>

    <%= f.submit '更新する', class: 'btn btn-primary' %>
  <% end %>
</div>

app/views/unread_books/index.html.erb
<div class="books_wrapper">

  <div class="container">
    <div class="row">
      <div class="col-sm-2 search-index-form">
        <h5 class="index-search-title">書籍検索</h5>
        <%= search_form_for @q do |f| %>
          <div class="form-group index-search">
            <%= f.label :title_or_author_cont, 'キーワード', class: 'bmd-label-floating' %>
            <%= f.search_field :title_or_author_cont, class: 'form-control' %>
          </div>

          <div class="form-group select-form">
            <%= f.label :status_eq, 'ステータス', class: 'bmd-label-floating' %>
            <%= f.select :status_eq, UnreadBook.statuses.map {|k, v| [I18n.t("enums.unread_book.status.#{k}"), v]}, { include_blank: true, selected: '' }, {class: 'custom-select'} %>
          </div>

          <%= f.submit '検索', class: 'btn btn-primary btn-raised' %>
        <% end %>
        <%= link_to '検索結果を戻す', unread_books_path, class: 'btn btn-warning', data: {turbolinks: false} %>
      </div>

      <div class="col-sm-10 index-table">
        <div class="index-table-content">
          <h2 class="unread-top">未読書籍一覧</h2>
          <div class="table-responsive">
            <table class="table table-striped">
              <thead>
                <tr>
                  <th class="book-title"style="width: 30%">書籍名</th>
                  <th class="book-description" style="width: 20%">著者名</th>
                  <th class="book-description" style="width: 15%">ステータス</th>
                  <th class="book-description" style="width: 20%">読破予定期間</th>
                  <th class="book-flag" style="width: 15%">読書フラグ</th>
                </tr>
              </thead>
              <tbody>
                <% @unread_books.each do |book| %>
                  <tr>
                    <td class="book-title"><%= link_to book.title, unread_book_path(book), class: 'book-info', data: {turbolinks: false} %></td>
                    <td class="book-description" ><%= book.author %></td>
                    <td class="book-description"><%= book.status_i18n %></td>
                    <% if book.reading_expired.present? %>
                      <td class="book-description"><%= book.reading_expired %></td>
                    <% else %>
                      <td class="book-description">未設定</td>
                    <% end %>
                    <% if book.reading? %>
                      <td class="book-flag"><%= link_to '積読へ', cancel_reading_unread_book_path(book), method: :patch, class: 'btn btn-secondary btn-raised' %></td>
                    <% else %>
                      <td class="book-flag"><%= link_to '読書中', reading_unread_book_path(book), method: :patch, class: 'btn btn-info btn-raised' %></td>
                    <% end %>
                  </tr>
                <% end %>
              </tbody>
            </table>
          </div>

        <%= paginate @unread_books %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/unread_books/new.html.erb
<h2 class="unread-top">新規未読書籍登録画面</h2>

<% if @unread_book.errors.present? %>
  <ul>
    <% @unread_book.errors.full_messages.each do |msg|%>
      <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>

<div class="unread_form_wrapper">
  <%= form_with model: @unread_book, local: true do |f| %>
    <div>
      <% if @book_image.present? %>
        <%= image_tag @book_image, size: '140x200' %>
        <p>by Google Search </p>
        <%= f.hidden_field :image_cache %>
      <% else %>
        <%= image_tag "no_image.png", size: '140x200' %>
      <% end %>
      <%= f.hidden_field :image, value: @book_image %>
    </div>

    <div class="form-group">
      <%= f.label :title, class: 'bmd-label-floating' %>
      <%= f.text_field :title, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= f.label :author, class: 'bmd-label-floating' %>
      <%= f.text_field :author, class: 'form-control' %>
    </div>


    <div class="form-group select-form">
      <%= f.label :status, class: 'bmd-label-floating' %>
      <%= f.select :status, UnreadBook.statuses.keys.map {|k| [I18n.t("enums.unread_book.status.#{k}"), k]}, { selected: UnreadBook.statuses[@unread_book.status] }, {class: 'custom-select'} %>
    </div>

    <div class="form-group select-date">
      <%= f.label :reading_expired, class: 'bmd-label-floating' %>
      <%= f.date_field :reading_expired %>
    </div>

    <div class="form-group">
      <%= f.label :tag_list, class: 'bmd-label-floating' %>
      <%= text_field_tag 'unread_book[tag_list]', @unread_book.tag_list.join(","), class: 'form-control', placeholder: 'タグを複数入力する場合は「,」で区切ってください' %>
    </div>

    <%= f.submit '登録する', class: 'btn btn-primary' %>
  <% end %>
</div>

app/views/unread_books/reading.html.erb
<table>
  <tr>
    <th>書籍名</th>
    <th>著者名</th>
    <th>読破期限</th>
    <th>未読書籍に戻す</th>
    <th>読破ボタン</th>
  </tr>
  <% @reading_books.each do |book| %>
    <tr>
      <td><%= book.title %></td>
      <td><%= book.author %></td>
      <td><%= book.reading_expired %></td>
      <td><%= link_to '未読へ', return_unread_book_path(book), method: :patch, data: { confirm: '本当に未読に戻しますか？'}  %></td>
      <td></td>
    </tr>
  <% end %>
</table>

app/views/unread_books/reading_books.html.erb
<h2 class="unread-top">読書中書籍一覧</h2>
<div class="container">
  <div class="row">
      <% @reading_books.each do |book| %>
        <div class="col-sm-6 mb-5">
          <div class="card">
            <div class="row">
              <div class="image-wrapper col-sm-4">
                <% if book.image.present? %>
                  <%= image_tag book.image.url ,size: '140x200', class: 'mr-3 search-image' %>
                  <span class="google-note">by Google Search</span>
                <% else %>
                  <%= image_tag "no_image.png", size: '140x200', class: 'mr-3 search-image' %>
                <% end %>
              </div>
              <div class="media-body col-sm-8">
                <h6 class="mt-2 mb-1">書籍名：<%= book.title %></h6>
                <h6 class="mt-2 mb-1">著者名：<%= book.author %></h6>
                <h6 class="mt-2 mb-1">読破期限：<%= book.reading_expired %></h6>
                <%= link_to '未読に戻す', return_unread_book_path(book), method: :patch, data: { confirm: '本当に未読に戻しますか？', turbolinks: false}, class: 'btn btn-warning'  %>
                <%= link_to '書籍読破', new_finished_book_path(params: { id: book.id, title: book.title, author: book.author, image: book.image, tags: book.tag_list  }), data: { turbolinks: false }, class: 'btn btn-success btn-lg btn-raised'  %>
              </div>
            </div>
          </div>
        </div>
      <% end %>
  </div>
</div>
<%= paginate @reading_books %>

<div class="progress-wrapper">
  <h3 class="unread-top"><i class="material-icons progress-icon"> event_note </i>進捗メモ一覧</h3>

  <div id="progress-form">
    <%= render partial: 'progresses/form', locals: { progress: @progress } %>
  </div>

  <div id="progress-view">
    <%= render partial: 'progresses/index', locals: { progresses: @progresses } %>
  </div>

</div>

app/views/unread_books/search.html.erb
<h2 class="unread-top">登録書籍検索</h2>
<p class="google-phrase text-muted">本サービスはGoogleBooksAPIを使用しております</p>
<%= form_tag search_unread_books_path, method: :get do %>
  <div class="search-wrapper">
    <div class="form-search">
      <div class="form-group input-search">
        <%= search_field_tag :looking_for, nil, { class: 'form-control', placeholder: '書籍名'} %>
        <%= hidden_field_tag :number, 0 %>
      </div>

      <%= submit_tag '検索', class: 'btn btn-primary btn-raised' %>
    </div>
  </div>
<% end %>
<% if @search_term.nil? %>
  <h3 class="search-info">購入した書籍を検索しましょう！</h3>
<% end %>

<% if @search_books.present? %>
  <% if @max_books > 15 %>
    <nav aria-label="Page navigation example">
      <ul class="pagination justify-content-center">
        <li class="page-item">
          <%= link_to '戻る', search_unread_books_path(looking_for: @search_term, number: @number - 10), data: {turbolinks: false}, class: 'page-link' if @number >= 1 %>
        </li>
        <li class="page-item">
          <%= link_to '次へ', search_unread_books_path(looking_for: @search_term, number: @number + 10), class: 'page-link', data: {turbolinks: false} %>
        </li>
      </ul>
    </nav>
  <% end %>
  <div class="container">
    <div class="row">
        <% @search_books.each do |book| %>
          <div class="col-sm-6 mb-5">
            <div class="card">
              <div class="row">
                <div class="image-wrapper col-4">
                  <% if book[:image].present? %>
                    <%= image_tag book[:image],size: '140x200', class: 'mr-3 search-image' %>
                    <span class="google-note">by Google Search</span>
                  <% else %>
                    <%= image_tag "no_image.png", size: '140x200', class: 'mr-3 search-image' %>
                  <% end %>
                </div>
                <div class="media-body col-8">
                  <h6 class="mt-2 mb-1 search-book">書籍名：<%= book[:title] %></h6>
                  <h6 class="mt-2 mb-1 search-book">著者名：<%= book[:author] %></h6>
                  <p class="search-link"><%= link_to '未読書籍へ登録', new_unread_book_path(title: book[:title], author: book[:author], image: book[:image]), class: 'btn btn-success', data: {turbolinks: false} %></p>
                </div>
              </div>
            </div>
          </div>
        <% end %>
    </div>
  </div>
  <% if @max_books > 15 %>
    <nav aria-label="Page navigation example">
      <ul class="pagination justify-content-center">
        <li class="page-item">
          <%= link_to '戻る', search_unread_books_path(looking_for: @search_term, number: @number - 10), data: {turbolinks: false}, class: 'page-link' if @number >= 1 %>
        </li>
        <li class="page-item">
          <%= link_to '次へ', search_unread_books_path(looking_for: @search_term, number: @number + 10), class: 'page-link', data: {turbolinks: false} %>
        </li>
      </ul>
    </nav>
  <% end %>
<% elsif @search_term.present? %>
  <p><%= @search_term %>による書籍は見つかりませんでした。</p>
<% end %>

app/views/unread_books/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-3">
      <div class="card top-card">
        <div class="card-header">
          <%= "#{current_user.name} さんのステータス" %>
        </div>
        <ul class="list-group list-group-flush">
          <li class="list-group-item">直近30日の読破数: <%= current_user.finished_books.where(created_at: DateTime.now - 30..DateTime.now).count %>冊 </li>
          <li class="list-group-item">読破済み書籍数: <%= current_user.finished_books.count %>冊</li>
          <li class="list-group-item list-alert">処分期限超過書籍数: <%= current_user.finished_books.where('status = ? AND desposal_expired < ?', 2, DateTime.now).count %>冊</li>
        </ul>
        <div class="card-footer">
          <small><%= link_to 'マイページ', user_path(current_user), class: 'btn btn-primary' %> </small>
        </div>
      </div>
    </div>
    <div class="col-sm-9">
      <h2 class="unread-top">書籍詳細画面</h2>
      <div class="card unread-card">
        <div class="responsive-show">
          <div class="row">
            <div class="col-sm-4">
              <div class="book-show-img">
                <% if @unread_book.image.present? %>
                  <%= image_tag @unread_book.image.url, size: '140x200' %><br>
                  <span class="google-note">by Google Search</span>
                <% else %>
                  <%= image_tag "no_image.png", size: '140x200' %>
                <% end %>
              </div>
            </div>
            <div class="col-sm-8">
              <ul class="unread-list">
                <li class="unread-content">書籍名：<%= @unread_book.title %></li>
                <li class="unread-content">著者名：<%= @unread_book.author %></li>
                <% if @unread_book.reading_expired.present? %>
                  <li class="unread-content">読破期限：<%= @unread_book.reading_expired %></li>
                <% else %>
                  <li class="unread-content">読破期限：未設定</li>
                <% end %>
                <li class="unread-content">ステータス：<%= I18n.t("enums.unread_book.status")[:"#{@unread_book.status}"] %></li>
                <% if @unread_book.tags.present? %>
                  <li class="unread-content">
                    タグ：<% @unread_book.tags.each do |tag|%>
                    <span class="book-tag badge badge-pill badge-primary"><%= tag %></span>
                  <% end %>
                  </li>
                <% end %>
              </ul>
              <%= link_to '編集する', edit_unread_book_path(@unread_book), class: 'btn btn-info', data: {turbolinks: false} %>
              <%= link_to '削除する', unread_book_path(@unread_book), method: :delete, data: {confirm: '本当に削除しますか？'}, class: 'btn btn-danger' %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/unread_books/tops.html.erb
<h2>トップページ</h2>

<% if user_signed_in? %>
  <%= link_to '未読書籍一覧画面へ', unread_books_path %>
  <%= link_to '読書中書籍一覧へ', reading_books_unread_books_path %>
  <%= link_to '既読書籍一覧へ', finished_books_path %>
  <%= link_to 'メッセージスレッドへ', conversations_path %>
  <%= link_to 'プロフィール編集', edit_user_registration_path %>
  <%= link_to '他ユーザーが読んだ書籍一覧', others_books_finished_books_path %>
  <%= link_to 'マイページ', user_path(current_user) %>
  <%= link_to '未読書籍検索', search_unread_books_path %>
  <%= link_to 'みんなが処分予定の書籍', planning_disposal_books_finished_books_path %>
<% end %>